big refactor, using json config file now

diff --git a/stax b/stax
--- a/stax
+++ b/stax
@@ -7,11 +7,14 @@ set -e
 #   https://github.com/philcryer/stax/blob/master/LICENSE
 #               "this should work(tm)!"
 #
-#TODO
+#   TODO
 #   * better formating with more (specific) details in jq output
+#   * dance like no ones watching
 #   * learn conversational german
 ##################################################################
 
+STAX_PRE_NAME="stax"
+COREOS_CHANNEL="alpha"
 SCRIPT_PATH=$( cd $(dirname $0) ; pwd -P )
 
 stax-colors(){
@@ -60,62 +63,37 @@ stax-existing(){
 
 stax-preflight(){
   which jq > /dev/null 2>&1 || { echo "jq (commandline JSON processor) is not installed. Aborting."; exit 1; }
-  echo "${yellow}[  ${green}ok${yellow}  ]${reset} jq installed"
   which aws > /dev/null 2>&1 || { echo "awscli is not installed. Aborting."; exit 1; }
-  echo "${yellow}[  ${green}ok${yellow}  ]${reset} awscli installed"
   if [ ! -f ${HOME}/.aws/config ]; then
      echo "awscli not configured, run 'aws configure'. Aborting."; exit 1
   fi
-  echo "${yellow}[  ${green}ok${yellow}  ]${reset} awscli configured"
-  if [ ! -d ~/.stax ]; then
-    mkdir ~/.stax
+  if [ ! -f config.json ]; then
+     echo "config.json not configured, copy example and configure'. Aborting."; exit 1
   fi
-  echo "${yellow}[  ${green}ok${yellow}  ]${reset} stax config dir available"
-  if [ ! -f ~/.stax/config ]; then
-    cp config/stax-config ${HOME}/.stax/config
-  fi
-  echo "${yellow}[  ${green}ok${yellow}  ]${reset} stax config file available"
-  echo "${yellow}[  ${green}ok${yellow}  ]${reset} sourcing config file"
-  stax-config
-  aws ec2 describe-key-pairs --key-names $STACK_KEY_PAIR --region $STACK_REGION > /dev/null 2>&1 || { echo "${yellow}[ ${red}ERRR${yellow} ]${reset} keypair $STACK_KEY_PAIR does not exit."; exit 1; }
-}
-
-stax-config(){
-  source ${HOME}/.stax/config
 }
 
 stax-summary(){
   echo "${yellow}[ ${cyan}----${yellow} ]${reset} stax summary"
-  echo "${yellow}[ ${blue}info${yellow} ]${reset} stax name: $STACK_NAME"
-  echo "${yellow}[ ${blue}info${yellow} ]${reset} instance type: $STACK_INSTANCE_TYPE"
-  echo "${yellow}[ ${blue}info${yellow} ]${reset} cluster size: $STACK_CLUSTER_SIZE nodes"
-  echo "${yellow}[ ${blue}info${yellow} ]${reset} discovery url: $STACK_DISCOVERY_URL"
-  echo "${yellow}[ ${blue}info${yellow} ]${reset} ec2 key pair: $STACK_KEY_PAIR"
-  echo "${yellow}[ ${blue}info${yellow} ]${reset} ssh from ip: $STACK_SSHFROM"
+  echo "${yellow}[ ${blue}info${yellow} ]${reset} stax name: $STAX_NAME"
+  echo "${yellow}[ ${blue}info${yellow} ]${reset} discovery url: $DISCOVERY_URL"
+  echo "${yellow}[ ${blue}info${yellow} ]${reset} allow ssh from: $SSH_FROM"
 }
 
 stax-create(){
   stax-generate
-  STACK_NAME="$STACK_PRE_NAME-$RANDOM_NUM-$RANDOM_NAM"
-  echo $STACK_NAME > ~/.stax/stax-name
-  echo "${yellow}[ ${cyan}----${yellow} ]${reset} creating $STACK_CLUSTER_SIZE nodes - $STACK_NAME"
-  aws --no-verify-ssl --color on cloudformation create-stack \
-    --region $STACK_REGION \
-    --stack-name $STACK_NAME \
+  STAX_NAME="$STAX_PRE_NAME-$RANDOM_NUM-$RANDOM_NAM"
+  echo $STAX_NAME > ~/.stax/stax-name
+  echo "${yellow}[ ${cyan}----${yellow} ]${reset} creating $CLUSTER_SIZE nodes - $STAX_NAME"
+  aws --color on cloudformation create-stack \
+    --stack-name $STAX_NAME \
     --template-body file://$SCRIPT_PATH/templates/cloudformation-template-$COREOS_CHANNEL.json \
-    --parameters \
-      "ParameterKey=InstanceType,ParameterValue=$STACK_INSTANCE_TYPE,UsePreviousValue=false" \
-      "ParameterKey=ClusterSize,ParameterValue=$STACK_CLUSTER_SIZE,UsePreviousValue=false" \
-      "ParameterKey=DiscoveryURL,ParameterValue=$STACK_DISCOVERY_URL,UsePreviousValue=false" \
-      "ParameterKey=AdvertisedIPAddress,ParameterValue=private,UsePreviousValue=false" \
-      "ParameterKey=AllowSSHFrom,ParameterValue=$STACK_SSHFROM,UsePreviousValue=false" \
-      "ParameterKey=KeyPair,ParameterValue=$STACK_KEY_PAIR,UsePreviousValue=false"
+    --parameters "$(<config.json.tmp)"
 }
 
 stax-describe(){
-  aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null 2>&1 || { echo "${yellow}[ ${cyan}----${yellow} ]${reset} no stax defined"; rm $HOME/.stax/stax-name; exit 1; }
-  echo "${yellow}[ ${cyan}----${yellow} ]${reset} describe $STACK_NAME"
-  aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null && aws cloudformation describe-stacks --stack-name $STACK_NAME --output table
+  aws cloudformation describe-stacks --stack-name $STAX_NAME > /dev/null 2>&1 || { echo "${yellow}[ ${cyan}----${yellow} ]${reset} no stax defined"; rm $HOME/.stax/stax-name; exit 1; }
+  echo "${yellow}[ ${cyan}----${yellow} ]${reset} describe $STAX_NAME"
+  aws cloudformation describe-stacks --stack-name $STAX_NAME > /dev/null && aws cloudformation describe-stacks --stack-name $STAX_NAME --output table
 }
 
 stax-list(){
@@ -131,14 +109,15 @@ stax-getip(){
 }
 
 stax-destroy(){
-  aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null && aws cloudformation delete-stack --stack-name $STACK_NAME 
-  rm $HOME/.stax/$STACK_NAME.json > /dev/null
+  aws cloudformation describe-stacks --stack-name $STAX_NAME > /dev/null && aws cloudformation delete-stack --stack-name $STAX_NAME 
+  rm $HOME/.stax/$STAX_NAME.json > /dev/null
   rm $HOME/.stax/stax-name > /dev/null
 }
 
 stax-generate(){
-  STACK_DISCOVERY_URL=$(curl -s http://discovery.etcd.io/new)
-  STACK_SSHFROM="$(curl -s http://icanhazip.com)/32"
+  cp config.json config.json.tmp
+  SSH_FROM="$(curl -s http://icanhazip.com)\/32"; sed -i "s/SSH_FROM/${SSH_FROM}/g" config.json.tmp
+  DISCOVERY_URL="$(curl -s http://discovery.etcd.io/new)"; sed -i "s|DISCOVERY_URL|${DISCOVERY_URL}|g" config.json.tmp
   NUMW=`wc -l < config/stax-words`
   RANDOM_NAM=`head -$((${RANDOM} % ${NUMW} + 1)) config/stax-words | tail -1`
   RANDOM_NUM=$((RANDOM%99999+10001))
@@ -150,7 +129,7 @@ stax-logo
 stax-preflight
 
 if [ -f $HOME/.stax/stax-name ]; then
-  STACK_NAME=`cat $HOME/.stax/stax-name`
+  STAX_NAME=`cat $HOME/.stax/stax-name`
 fi
 
 if [[ "$1" == "dryrun" ]]; then
@@ -168,8 +147,8 @@ if [[ "$1" == "create" ]]; then
   else
     stax-create
     stax-describe
-    aws cloudformation describe-stacks --stack-name $STACK_NAME > ~/.stax/$STACK_NAME.json
-    echo "${yellow}[ ${cyan}----${yellow} ]${reset} creation complete"
+    aws cloudformation describe-stacks --stack-name $STAX_NAME > ~/.stax/$STAX_NAME.json
+    rm config.json.tmp
     exit 0
   fi
 fi
@@ -186,25 +165,19 @@ fi
 
 if [[ "$1" == "getip" ]]; then
   stax-existing
-  stax-summary
-  if [ -f $HOME/.stax/stax-name ]; then
-    stax-getip
-  else
-    echo "${yellow}[ ${red}ERRR${yellow} ]${reset} no stax defined, use create first"
-    exit 1
-  fi
+  stax-getip
 fi
 
 if [[ "$1" == "destroy" ]]; then
   stax-existing
   if [ -f $HOME/.stax/stax-name ]; then
-    read -p "${yellow}[ ${cyan}????${yellow} ]${reset} ok to destroy $STACK_NAME [y/n]? " answer
+    read -p "${yellow}[ ${cyan}????${yellow} ]${reset} ok to destroy $STAX_NAME [y/n]? " answer
     if [[ $answer = y ]] ; then
         stax-destroy
-        echo "${yellow}[ ${cyan}----${yellow} ]${reset} $STACK_NAME will be destroyd"
+        echo "${yellow}[ ${cyan}----${yellow} ]${reset} $STAX_NAME will be destroyd"
     fi
   else
-    echo "${yellow}[ ${cyan}----${yellow} ]${reset} could not destroy $STACK_NAME, check name"
+    echo "${yellow}[ ${cyan}----${yellow} ]${reset} could not destroy $STAX_NAME, check name"
     exit 1
   fi
 fi
