added templates, config file

diff --git a/stax b/stax
--- a/stax
+++ b/stax
@@ -1,28 +1,63 @@
 #!/bin/bash
 
-which aws > /dev/null 2>&1 || { echo "aws cli it's not installed.  Aborting."; exit 1; }
+##################################################################
+#   S     t     a     x   (for aws ec2)
+#   https://github.com/philcryer/stax
+#   https://github.com/philcryer/stax/blob/master/LICENSE
 
-if [ ! -d ~/.stax ]; then
-  mkdir ~/.stax
-fi
+# colours http://misc.flogisoft.com/bash/tip_colors_and_formatting
+# [ ok ] - echo -e '\e[33m[ \e[32mok\e[33m ]\e[39m'
+#
+##################################################################
 
-# Default values. All can be replaced by command line arguments.
-SCRIPT_PATH=$( cd $(dirname $0) ; pwd -P )
-STACK_NAME="coreos-pool-$RANDOM"
-STACK_DISCOVERY_URL=$(curl -s https://discovery.etcd.io/new)
-#STACK_INSTANCE_TYPE="m3.medium"
-STACK_INSTANCE_TYPE="t2.micro"
-STACK_CLUSTER_SIZE=3
-STACK_KEY_PAIR="pccrye-20141005"
-#STACK_REGION="us-west-2"
-STACK_REGION="us-east-1"
-STACK_SSHFROM=$(curl -s ipecho.net/plain)/32
+function stax-logo(){
+  echo -e '\e[31m     _             '
+  echo -e '    | | \e[33mfor aws ec2\e[31m'
+  echo ' ___| |_ __ ___  __'
+  echo '/ __| __/ _` \ \/ /'
+  echo '\__ \ || (_| |>  < '
+  echo '|___/\__\__,_/_/\_\'
+  echo -e '\e[39m'
+}
+
+clear
+stax-logo
+
+function stax-preflight(){
+  # awscli check
+  which aws > /dev/null 2>&1 || { echo "awscli is not installed. Aborting."; exit 1; }
+  echo -e '\e[33m[ \e[32mok\e[33m ]\e[39m awscli installed'
+  # awscli config check
+  if [ ! -f ${HOME}/.aws/config ]; then
+     echo "awscli not configured, run 'aws configure'. Aborting."; exit 1
+  fi
+  echo -e '\e[33m[ \e[32mok\e[33m ]\e[39m awscli configured'
+  # stax dot dir check
+  if [ ! -d ~/.stax ]; then
+    mkdir ~/.stax
+  fi
+  echo -e '\e[33m[ \e[32mok\e[33m ]\e[39m stax config dir available'
+  # stax config check
+  if [ ! -f ~/.stax/config ]; then
+    cp config/stax-config ${HOME}/.stax/config
+  fi
+  echo -e '\e[33m[ \e[32mok\e[33m ]\e[39m stax config file available'
+}
+
+stax-preflight
+
+echo
 
 dryrun=0
 
 help(){
     echo "create-stack [-s <stack-name>] -k <keypair-name> -u <discovery-toten-url> -r region -t <ec2-type> -n <ec2-number> -d "
 }
+
+source ${HOME}/.stax/config
+
+exit 0
+
 
 while getopts "s:k:u:r:t:n:dh" OPTION
 do
@@ -55,20 +90,20 @@ do
     esac
 done
 
-aws ec2 describe-key-pairs --key-names $STACK_KEY_PAIR > /dev/null 2>&1 || { echo "Keypair $STACK_KEY_PAIR does not exit."; exit 1; }
+aws ec2 describe-key-pairs --key-names $STACK_KEY_PAIR --region $STACK_REGION > /dev/null 2>&1 || { echo "Keypair $STACK_KEY_PAIR does not exit."; exit 1; }
 
-echo "Creating CloudFormation Stack with these parameters:"
-echo -n "Aws-cli: $AWS_CLI_VERSION"
-$AWS_CLI_VERSION`aws --version`
+echo "Stax setup:"
+AWS_CLI_VERSION=`aws --version`
+echo "Aws-cli: $AWS_CLI_VERSION"
 echo "Name: $STACK_NAME"
 echo "Discovery URL: $STACK_DISCOVERY_URL"
 echo "Instance Type x Cluster Size: $STACK_INSTANCE_TYPE x $STACK_CLUSTER_SIZE"
 echo "EC2 Key Pair: $STACK_KEY_PAIR"
 echo "SSH From: $STACK_SSHFROM"
-if [ ${1} == 'create' ]; then
-  echo "go"
-fi
 
+#if [ ${1} == 'create' ]; then
+#  echo "go"
+#fi
 
 [ $dryrun -eq 1 ] && { echo "Dryrun only."; exit 0; }
 
@@ -77,7 +112,7 @@ echo "$STACK_NAME" > ~/.stax/stack_name
 aws --no-verify-ssl --color on cloudformation create-stack \
   --region $STACK_REGION \
   --stack-name $STACK_NAME \
-  --template-body file://$SCRIPT_PATH/cloudformation-template.json \
+  --template-body file://$SCRIPT_PATH/templates/cloudformation-template-$COREOS_CHANNEL.json \
   --parameters \
     "ParameterKey=InstanceType,ParameterValue=$STACK_INSTANCE_TYPE,UsePreviousValue=false" \
     "ParameterKey=ClusterSize,ParameterValue=$STACK_CLUSTER_SIZE,UsePreviousValue=false" \
@@ -86,6 +121,41 @@ aws --no-verify-ssl --color on cloudformation create-stack \
     "ParameterKey=AllowSSHFrom,ParameterValue=$STACK_SSHFROM,UsePreviousValue=false" \
     "ParameterKey=KeyPair,ParameterValue=$STACK_KEY_PAIR,UsePreviousValue=false"
 
-
-
 exit 0
+
+
+
+
+
+ ___  ____   __    _  _ 
+/ __)(_  _) /__\  ( \/ )
+\__ \  )(  /(__)\  )  ( 
+(___/ (__)(__)(__)(_/\_)
+
+
+
+     _             
+    | |            
+ ___| |_ __ ___  __
+/ __| __/ _` \ \/ /
+\__ \ || (_| |>  < 
+|___/\__\__,_/_/\_\
+                   
+            
+
+
+     _             
+ ___| |_ __ ___  __
+/ __| __/ _` \ \/ /
+\__ \ || (_| |>  < 
+|___/\__\__,_/_/\_\
+                   
+
+
+
+ ___  ____  __   _  _ 
+/ __)(_  _)(  ) ( \/ )
+\__ \  )(  /__\  )  ( 
+(___/ (__)(_)(_)(_/\_)
+
+}
