stax: improve json parsing, add dockerip-update to account for changes when autoscaling happens

diff --git a/stax b/stax
--- a/stax
+++ b/stax
@@ -109,6 +109,7 @@ Commands:
   create             Create a new VPC stax in AWS
   describe           Describe the stax created from this host
   destroy            Destroy the existing VPC stax
+  dockerip-update    Destroy the existing VPC stax
   fleet              Run various fleetctl commands against the fleet cluster
   generate           Regenerate the VPC template from the Scala definition
   help               Output this message
@@ -419,7 +420,8 @@ EOF
 # ensure there is a stax
 stax-existing(){
     if [[ ! -f $STAX_NAME_FILE ]]; then
-        stax-error-exit "no stax defined, use create first" 1
+        stax-error "no stax defined, use create first"
+        return 1
     fi
     # define all the global variables
     STAX_NAME=$(<$STAX_NAME_FILE)
@@ -460,8 +462,8 @@ stax-complete(){
             stax-error "unable to get information about stax $STAX_NAME"
             return 1
         fi
-        status=$($jq '.Stacks[].StackStatus' "$STAX_DESC")
-        if [[ $status == '"CREATE_COMPLETE"' ]]; then
+        status=$($jq --raw-output '.Stacks[].StackStatus' "$STAX_DESC")
+        if [[ $status == CREATE_COMPLETE ]]; then
             break
         fi
         stax-message "  stax build not complete: $status"
@@ -479,7 +481,7 @@ stax-list(){
     stax-message "list currently running stax"
     stax-message "  querying aws "
     # list running stax
-    if ! aws --output json cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | $jq '.StackSummaries[].StackName' | grep "vpc-stax" | cut -d"\"" -f2 > /tmp/run.list; then
+    if ! aws --output json cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | $jq --raw-output '.StackSummaries[].StackName' | grep '^vpc-stax-' > /tmp/run.list; then
         stax-error "  aws query failed"
         return 1
     fi
@@ -632,13 +634,12 @@ stax-getdockerips(){
     stax-message "get router and service IP(s)"
     stax-message "  querying aws"
     service_hosts="$STAX_DIR/$STAX_NAME.service_hosts"
-    # this will not print the IP address of a host if it is the last host in the list
-    if ! aws --output json ec2 describe-instances --output text --query 'Reservations[*].Instances[*]' | awk "\$1 == \"0\" { if (ip != \"\" && name == \"container-$STAX_NAME\") print ip; ip = \"\" } \$1 == \"PRIVATEIPADDRESSES\" { ip = \$NF } \$1 == \"TAGS\" && \$2 == \"Name\" { name = \$3 }" > "$service_hosts"; then
+    if ! aws --output json ec2 describe-instances | $jq --raw-output ".Reservations[].Instances[] | select(.Tags[].Value==\"container-$STAX_NAME\").PrivateIpAddress" > "$service_hosts"; then
         stax-error "failed to query aws for service instances"
         return 1
     fi
     router_hosts="$STAX_DIR/$STAX_NAME.router_hosts"
-    if ! aws --output json ec2 describe-instances --output text --query 'Reservations[*].Instances[*]' | awk "\$1 == \"0\" { if (ip != \"\" && name == \"router-$STAX_NAME\") print ip; ip = \"\" } \$1 == \"PRIVATEIPADDRESSES\" { ip = \$NF } \$1 == \"TAGS\" && \$2 == \"Name\" { name = \$3 }" > "$router_hosts"; then
+    if ! aws --output json ec2 describe-instances | $jq --raw-output ".Reservations[].Instances[] | select(.Tags[].Value==\"router-$STAX_NAME\").PrivateIpAddress" > "$router_hosts"; then
         stax-error "failed to query aws for router instances"
         return 1
     fi
@@ -1049,27 +1050,63 @@ case "$sub_cmd" in
 
     create)
         stax-create "$template"
-        stax-existing
-        stax-motd
-        stax-describe
+        if ! stax-existing; then
+            stax-error-exit "stax create failed" 1
+        fi
+        if ! stax-motd; then
+            stax-error-exit "failed to create motd file" 1
+        fi
+        if ! stax-describe; then
+            stax-error-exit "failed to get stack information from aws" 1
+        fi
         ;;
 
     desc-auto)
-        stax-existing
+        if ! stax-existing; then
+            exit 1
+        fi
         stax-descauto
         ;;
 
     desc*)
-        stax-existing
+        if ! stax-existing; then
+            exit 1
+        fi
         if ! stax-describe; then
             stax-error-exit "stax describe failed" 1
         fi
         ;;
 
     destroy)
-        stax-existing
+        if ! stax-existing; then
+            exit 1
+        fi
         if ! stax-destroy $sub_cmd_args; then
             stax-error-exit "please see above errors and deal with them" 1
+        fi
+        ;;
+
+    dockerip-update)
+        if ! stax-existing; then
+            exit 1
+        fi
+        if ! stax-complete; then
+            stax-error-exit "stax build not complete" 1
+        fi
+        if [[ ! -f $STAX_JUMP_FILE ]]; then
+            stax-jumpip
+            stax-getdockerips
+            stax-ssh-config
+            stax-popjumpbox
+        fi
+        STAX_PUB_IP=$(<$STAX_JUMP_FILE)
+        if ! stax-getdockerips; then
+            stax-error "failed to update docker IPs"
+            exit 1
+        fi
+        if ! stax-ssh-config; then
+            stax-error "failed to update ssh config"
+            exit 1
         fi
         ;;
 
