stax: revert ssh-agent check location/reporting, fully implement --template option

diff --git a/stax b/stax
--- a/stax
+++ b/stax
@@ -14,10 +14,15 @@ SYSTEM=$(uname)
 STAX_DIR="$SCRIPT_PATH/run"
 STAX_NAME_FILE="$STAX_DIR/stax-name"
 STAX_LOG="$STAX_DIR/stax.log"
-STAX_TEMPLATE_PATH="templates/cloudformation-template-vpc.json"
 SSH_OPTIONS="-q"
 host=$(hostname)
 YES=
+
+# make sure we are running under ssh-agent
+if [[ ! $SSH_AUTH_SOCK ]]; then
+    echo "$pkg: not running under ssh-agent, restarting with ssh-agent running"
+    exec ssh-agent $0 "$@"
+fi
 
 # create a dir to store stax stuff
 if [[ ! -d $STAX_DIR ]]; then
@@ -82,41 +87,36 @@ stax-logger(){
     echo "$(date +'%b %d %T') $host $pkg: $msg" >> "$STAX_LOG"
 }
 
-# make sure we are running under ssh-agent
-if [[ ! $SSH_AUTH_SOCK ]]; then
-    stax-logger "$pkg: not running under ssh-agent, restarting with ssh-agent running"
-    exec ssh-agent $0 "$@"
-fi
-
 stax-usage(){
     cat <<EOM
 Usage: stax [OPTIONS] <command>
 
 Options:
-  -c,--config=CONFIG        Use file CONFIG rather than config/config.json
-  -d,--debug                Turn on verbose messages
-  -h,--help                 Output this message
-  -t,--template=TEMPLATE    Use file TEMPLATE rather than templates/default.json
-  -v,--version              Print name and version information
-  -y,--yes                  Do not prompt for confirmation
+  -c,--config=CONFIG       Use file CONFIG rather than config/config.json
+  -d,--debug               Turn on verbose messages
+  -h,--help                Output this message
+  -j,--jump=IP             SSH through host with IP address IP
+  -t,--template=TEMPLATE   Use file TEMPLATE rather than templates/default.json
+  -v,--version             Print name and version information
+  -y,--yes                 Do not prompt for confirmation
 
 If an argument is required for a long option, so to the short. Same for
 optional arguments.
 
 Commands:
-  connect [target]  Connect to jump|router|service in the VPC stax over SSH
-  create            Create a new VPC stax in AWS
-  describe          Describe the stax created from this host
-  destroy           Destroy the existing VPC stax
-  fleet             Run various fleetctl commands against the fleet cluster
-  generate          Regenerate the VPC template from the Scala definition
-  help              Output this message
-  history           View history of recently created/destroyed stax
-  list              List all completely built and running stax
-  services          List servers that are available to run across a stax
-  start <service>   Start a service across the stax cluster
-  test              Automated test to exercise functionality of stax
-  validate          Validate CloudFormation template
+  connect [target]   Connect to jump|router|service in the VPC stax over SSH
+  create             Create a new VPC stax in AWS
+  describe           Describe the stax created from this host
+  destroy            Destroy the existing VPC stax
+  fleet              Run various fleetctl commands against the fleet cluster
+  generate           Regenerate the VPC template from the Scala definition
+  help               Output this message
+  history            View history of recently created/destroyed stax
+  list               List all completely built and running stax
+  services           List servers that are available to run across a stax
+  start <service>    Start a service across the stax cluster
+  test               Automated test to exercise functionality of stax
+  validate           Validate CloudFormation template
 
 For more help, check the docs: https://github.com/philcryer/stax
 EOM
@@ -210,10 +210,10 @@ stax-create-bucket(){
 }
 
 stax-upload-template(){
-    template_path="$STAX_TEMPLATE_PATH"
-    if [[ $1 ]]; then
-        template_path="$1"
+    if [[ ! $1 ]]; then
+        stax-error-exit "stax-upload-template requires the template path as an argument" 10
     fi
+    template_path="$1"
     if [[ ! -f $template_path ]]; then
         stax-error "template file not found: $template_path"
         return 1
@@ -246,17 +246,17 @@ stax-validate-template(){
 
 stax-validate(){
     stax-message "validate template"
-    template="$STAX_TEMPLATE_PATH"
-    if [[ $1 ]]; then
-        template="$1"
+    if [[ ! $1 ]]; then
+        stax-error-exit "stax-validate requires the template path as an argument" 10
     fi
+    template_path="$1"
     if ! stax-generate; then
         stax-error-exit "failed to set up stax" 1
     fi
     if ! stax-create-bucket; then
         stax-error-exit "failed to create bucket for upload" 1
     fi
-    if ! stax-upload-template; then
+    if ! stax-upload-template "$template_path"; then
         stax-destroy-bucket
         stax-error-exit "failed to upload template" 1
     fi
@@ -270,15 +270,20 @@ stax-validate(){
 }
 
 stax-create(){
+    stax-message "creating stax"
+    if [[ ! $1 ]]; then
+        stax-error-exit "stax-create takes the template path as an argument" 10
+    fi
+    template_path="$1"
     if [[ -f $STAX_NAME_FILE ]]; then
         existing_name=$(<$STAX_NAME_FILE)
-        stax-error-exit "existing stax defined: $existing_name" 1
+        stax-error "existing stax defined: $existing_name"
+        stax-error-exit "currently having only one stack is supportetd, exiting" 1
     fi
     if ! stax-generate; then
         stax-error-exit "failed to set up stax" 1
     fi
     stax-message "$STAX_NAME" "NAME"
-    stax-message "creating stax"
     if ! stax-config; then
         stax-error-exit "failed to generate stax config" 1
     fi
@@ -292,7 +297,7 @@ stax-create(){
         stax-error-exit "failed to create bucket" 1
     fi
     # upload template to s3 to have bigger size limits
-    if ! stax-upload-template; then
+    if ! stax-upload-template "$template_path"; then
         stax-destroy-bucket
         stax-destroy-key
         stax-destroy-files
@@ -316,19 +321,23 @@ stax-create(){
     done
     stax-message "  vpc assets uploaded"
     stax-message "  creating stax in aws"
+    # add --tags
     if ! aws cloudformation create-stack \
         --stack-name "$STAX_NAME" \
         --template-url "$STAX_TEMPLATE_URL" \
         --parameters "$(<$STAX_PARAMS)" \
         --capabilities CAPABILITY_IAM > /dev/null
     then
-        stax-error "creation failed, exiting"
+        stax-error "creation failed, cleaning up"
         stax-destroy-bucket
         stax-destroy-key
         stax-destroy-files
-        exit 2
+        stax-error-exit "creation failed, exiting" 1
     fi
-    echo $STAX_NAME > $STAX_NAME_FILE
+    if ! echo $STAX_NAME > $STAX_NAME_FILE; then
+        stax-error "failed to create STAX_NAME_FILE: echo $STAX_NAME > $STAX_NAME_FILE"
+        stax-error-exit "stax will not be able to function without it" 1
+    fi
     # new 'audit' functionality, save names and create date of stax you've created
     # if useful, we could save this to S3: and make it persist (well sure, uh, or the fax)
     if mkdir -p "$STAX_DIR/audit/$STAX_NAME"; then
@@ -742,10 +751,11 @@ stax-generate(){
 stax-config(){
     # verify config is filled out
     if [[ ! -f $config ]]; then
-        stax-error "$config does not exist, configuration required"
+        stax-error "config file does not exist: $config"
+        stax-error "configuration required"
         stax-error "copy example to config directory, configure it and run again."
         stax-error "    $ cp $config.example $config"
-        stax-error-exit "Aborting." 1
+        return 1
     fi
     stax-message "creating parameter file"
     # initialize sed command
@@ -754,41 +764,52 @@ stax-config(){
     if grep -q '@OWNER@' "$config" > /dev/null 2>&1; then
         owner="$(id -u -n)"
         if [[ -z $owner ]]; then
-            stax-error-exit "failed to determine user" 1
+            stax-error "failed to determine user"
+            return 1
         fi
         sed="$sed -e s/@OWNER@/$owner/"
     fi
-    if grep -q '@SSH_FROM@' "$config" > /dev/null 2>&1; then
-        SSH_FROM="$(curl -s http://icanhazip.com)/32"
-        if [ -z "$SSH_FROM" ]; then
-            stax-error-exit "failed to get IP address for local machine" 1
-        fi
-        sed="$sed -e s|@SSH_FROM@|$SSH_FROM|"
+    external_cidr="$(curl -s http://icanhazip.com)/32"
+    if [[ -z $external_cidr ]]; then
+        stax-error "failed to get IP address for local machine"
     fi
     if grep -q '@HTTP_FROM@' "$config" > /dev/null 2>&1; then
-        # same as SSH_FROM
-        sed="$sed -e s|@HTTP_FROM@|$SSH_FROM|"
+        sed="$sed -e s|@HTTP_FROM@|$external_cidr|"
+    fi
+    if grep -q '@SSH_FROM@' "$config" > /dev/null 2>&1; then
+        if [[ $jump ]]; then
+            ssh_from="$jump"
+        else
+            ssh_from="$external_cidr"
+        fi
+        sed="$sed -e s|@SSH_FROM@|$ssh_from|"
     fi
     if grep -q '@DISCOVERY_URL@' "$config" > /dev/null 2>&1; then
         DISCOVERY_URL="$(curl -s http://discovery.etcd.io/new)"
         if [[ -z $DISCOVERY_URL || $DISCOVERY_URL == 'Unable to generate token' ]]; then
-            stax-error-exit "failed to get discovery URL" 1
+            stax-error "failed to get discovery URL"
+            return 1
         fi
         sed="$sed -e s|@DISCOVERY_URL@|$DISCOVERY_URL|"
     fi
     STAX_PARAMS="$STAX_DIR/$STAX_NAME.params"
     if ! $sed "$config" > "$STAX_PARAMS"; then
-        stax-error-exit "sed failed to replace elements in $config: $sed" 1
+        stax-error "sed failed to replace elements in $config: $sed"
+        return 1
     fi
 }
 
 # automated test
 stax-test(){
     stax-message "running stax test"
+    if [[ ! $1 ]]; then
+        stax-error-exit "stax-test takes the template path as an argument" 10
+    fi
+    template_path="$1"
     stax-message "  create dummy parameter config"
     user=$(id -u -n)
     config="/tmp/test-config-$user-$$-$RANDOM.json"
-    cat > "$config" <<EOF
+    if ! cat > "$config" <<EOF
 [
   { "ParameterKey": "App",                 "ParameterValue": "Stax Auto Test" },
   { "ParameterKey": "Group",               "ParameterValue": "ITSA" },
@@ -801,9 +822,13 @@ stax-test(){
   { "ParameterKey": "DiscoveryURL",        "ParameterValue": "@DISCOVERY_URL@" }
 ]
 EOF
+    then
+        stax-error "failed to create test config file"
+        return 1
+    fi
     # loop through the setup commands
     for cmd in \
-        "stax-create" \
+        "stax-create $template_path" \
         "rm -f $config" \
         "stax-existing" \
         "stax-motd" \
@@ -862,11 +887,12 @@ EOF
     # fleetctl list-
 
     YES="y"
-    stax-destroy 1
+    stax-destroy
 }
 
 # process positional parameters
 config="config/config.json"
+template="templates/cloudformation-template-vpc.json"
 sub_cmd=
 sub_cmd_args=
 prev_arg=
@@ -970,7 +996,7 @@ case "$sub_cmd" in
         ;;
 
     create)
-        stax-create
+        stax-create "$template"
         stax-existing
         stax-motd
         stax-describe
@@ -1061,14 +1087,14 @@ case "$sub_cmd" in
         ;;
 
     test)
-        if ! stax-test; then
+        if ! stax-test "$template"; then
             stax-error "test failed, please delete stack yourself"
             exit 1
         fi
         ;;
 
     validate)
-        stax-validate $sub_cmd_args
+        stax-validate "$template"
         ;;
 
     *)
