YOU NEED TO UPDATE YOUR CONFIG AGAIN: ec2 key-pair now created and destroyed dynamically, see example config

diff --git a/stax b/stax
--- a/stax
+++ b/stax
@@ -18,6 +18,7 @@ STAX_NAME_FILE="$STAX_DIR/stax-name"
 #DEBUG="ON"
 config="config/config.json"
 config_tmp="/tmp/config.json"
+SSH_OPTIONS="-q -o StrictHostKeyChecking=no"
 
 stax-colors(){
   green=$(tput setaf 2)
@@ -70,21 +71,26 @@ stax-existing(){
 }
 
 stax-preflight(){
-  which aws > /dev/null 2>&1 || { echo "awscli is not installed. Aborting."; exit 1; }
-  if [ ! -f "$HOME/.aws/config" ]; then
-     echo "awscli not configured, run 'aws configure'. Aborting."; exit 1
-  fi
-  if [ ! -d "$STAX_DIR" ]; then
-      echo "creating directory $STAX_DIR"
-      mkdir -p "$STAX_DIR"
-  fi
-  if [ ! -f "$config" ]; then
-     echo "$pkg: $config does not exist, configuration required"
-     echo "$pkg: copy example to config directory, configure it and run again."
-     echo "    $ cp $config.example $config"
-     echo "$pkg: Aborting."
-     exit 1
-  fi
+    which aws > /dev/null 2>&1 || { echo "awscli is not installed. Aborting."; exit 1; }
+    if [ ! -f "$HOME/.aws/config" ]; then
+        echo "awscli not configured, run 'aws configure'. Aborting."
+        exit 1
+    fi
+    if [ ! -d "$STAX_DIR" ]; then
+        echo "creating directory $STAX_DIR"
+        mkdir -p "$STAX_DIR"
+    fi
+    if ! chmod 700 "$STAX_DIR"; then
+        echo "$pkg: failed to chmod $STAX_DIR"
+        exit 1
+    fi
+    if [ ! -f "$config" ]; then
+        echo "$pkg: $config does not exist, configuration required"
+        echo "$pkg: copy example to config directory, configure it and run again."
+        echo "    $ cp $config.example $config"
+        echo "$pkg: Aborting."
+        exit 1
+    fi
 }
 
 stax-validate(){
@@ -94,8 +100,21 @@ stax-validate(){
     echo "${yellow}[ ${red}ERRR${yellow} ]${reset}     template failed to validate, exiting"
     stax-destroy-bucket
     stax-destroy-files
+    stax-destroy-key
     exit 2
   fi
+}
+
+stax-create-key(){
+    STAX_KEY="$STAX_NAME"
+    STAX_KEY_FILE="$STAX_DIR/$STAX_NAME.pem"
+    touch "$STAX_KEY_FILE"
+    chmod 600 "$STAX_KEY_FILE"
+    # this would be better if we had a real json parser
+    echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     creating key pair: "
+    $aws ec2 create-key-pair --key-name "$STAX_NAME" --query 'KeyMaterial' --output text > "$STAX_KEY_FILE"
+    SSH_OPTIONS="$SSH_OPTIONS -i $STAX_KEY_FILE"
+    echo "done"
 }
 
 stax-create-bucket(){
@@ -109,6 +128,7 @@ stax-create(){
   stax-generate
   echo "${yellow}[ ${cyan}NAME${yellow} ]${reset} $STAX_NAME"
   echo "${yellow}[ ${cyan}----${yellow} ]${reset}   creating stax"
+  stax-create-key
   stax-create-bucket "$STAX_NAME"
   # upload template to s3 to have bigger size limits
   template="$STAX_NAME/$STAX_NAME.json"
@@ -122,6 +142,12 @@ stax-create(){
   #echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     validating template: "
   stax-validate "$template_url" > /dev/null
+  echo "done"
+  # upload vpc assets
+  echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     uploading vpc assets: "
+  for f in assets/vpc/*; do
+      $aws s3 cp "$f" "s3://$STAX_NAME/" > /dev/null
+  done
   echo "done"
   echo $STAX_NAME > $STAX_NAME_FILE
   echo "${yellow}[ ${cyan}----${yellow} ]${reset}     creating vpc in aws"
@@ -142,6 +168,7 @@ stax-create(){
     echo "${yellow}[ ${red}ERRR${yellow} ]${reset}     creation failed, exiting"
     stax-destroy-bucket
     stax-destroy-files
+    stax-destroy-key
     exit 2
   fi
 }
@@ -155,6 +182,7 @@ stax-describe(){
     echo "${yellow}[ ${cyan}----${yellow} ]${reset} stax $STAX_NAME does not exist in AWS"
     stax-destroy-bucket
     stax-destroy-files
+    stax-destroy-key
     exit 1
   fi
   echo "done"
@@ -191,13 +219,13 @@ stax-services(){
 stax-start-services(){
   echo "${yellow}[ ${cyan}----${yellow} ]${reset}   starting service(s) on the stax cluster"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     pushing service file to $STAX_PUB_IP: "
-  scp -q -i ~/.ssh/$STAX_KEY.pem /tmp/servicerunner ec2-user@$STAX_PUB_IP:~ > /dev/null
+  scp $SSH_OPTIONS /tmp/servicerunner ec2-user@$STAX_PUB_IP:~ > /dev/null
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     setting permissions on service file: "
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP 'chmod 755 servicerunner' > /dev/null
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP 'chmod 755 servicerunner' > /dev/null
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     running service file: "
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP 'sh servicerunner' > /dev/null
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP 'sh servicerunner' > /dev/null
   echo "done"
   rm /tmp/servicerunner*
   sleep 5
@@ -206,7 +234,7 @@ stax-start-services(){
 
 stax-fleetstats(){
   echo "${yellow}[ ${cyan}----${yellow} ]${reset}  status from fleetctl on the cluster: "
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP 'sh fleetstats'
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP 'sh fleetstats'
   #exit 0
 }
 
@@ -248,11 +276,10 @@ stax-getip(){
 stax-pushkey(){
   echo "${yellow}[ ${cyan}----${yellow} ]${reset}   push key to jumpbox"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     pushing key to $STAX_PUB_IP: "
-  STAX_KEY=`cat $STAX_DIR/$STAX_NAME.json | grep -B1 -A1 'KeyName'|grep "ParameterValue" | cut -d"\"" -f4`
-  scp -q -i ~/.ssh/$STAX_KEY.pem ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP:.ssh > /dev/null
+  scp $SSH_OPTIONS $STAX_KEY_FILE ec2-user@$STAX_PUB_IP:.ssh > /dev/null
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     setting permissions on key: "
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP 'chmod 0600 .ssh/*.pem' > /dev/null
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP 'chmod 0600 .ssh/*.pem' > /dev/null
   echo "done"
 }
 
@@ -276,13 +303,13 @@ stax-popjumpbox(){
     echo "${yellow}[ ${red}ERRR${yellow} ]${reset}     motd file not found, exiting";
     exit 1
   fi
-  scp -q -i ~/.ssh/$STAX_KEY.pem /tmp/motd ec2-user@$STAX_PUB_IP:~ > /dev/null
+  scp $SSH_OPTIONS /tmp/motd ec2-user@$STAX_PUB_IP:~ > /dev/null
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     pushing bashrc to $STAX_PUB_IP: "
-  scp -q -i ~/.ssh/$STAX_KEY.pem assets/stax/bashrc ec2-user@$STAX_PUB_IP:~/.bashrc > /dev/null
+  scp $SSH_OPTIONS assets/stax/bashrc ec2-user@$STAX_PUB_IP:~/.bashrc > /dev/null
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     copying service definitions to $STAX_PUB_IP: "
-  scp -q -r -i ~/.ssh/$STAX_KEY.pem assets/services ec2-user@$STAX_PUB_IP:~ > /dev/null
+  scp $SSH_OPTIONS -r assets/services ec2-user@$STAX_PUB_IP:~ > /dev/null
   echo "done"
   rm /tmp/motd
 }
@@ -302,11 +329,11 @@ stax-getdockerips(){
   sed "s|STAX_KEY|${STAX_KEY}|g" assets/stax/fleetstats > /tmp/fleetstats
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     putting docker files on jumpbox: "
-  scp -q -i ~/.ssh/$STAX_KEY.pem /tmp/docker_hosts ec2-user@$STAX_PUB_IP:~ > /dev/null
-  scp -q -i ~/.ssh/$STAX_KEY.pem /tmp/dockconnect ec2-user@$STAX_PUB_IP:~ > /dev/null
-  scp -q -i ~/.ssh/$STAX_KEY.pem /tmp/fleetstats ec2-user@$STAX_PUB_IP:~ > /dev/null
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP 'chmod 0755 dockconnect' > /dev/null
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP 'chmod 0755 fleetstats' > /dev/null
+  scp $SSH_OPTIONS /tmp/docker_hosts ec2-user@$STAX_PUB_IP:~ > /dev/null
+  scp $SSH_OPTIONS /tmp/dockconnect ec2-user@$STAX_PUB_IP:~ > /dev/null
+  scp $SSH_OPTIONS /tmp/fleetstats ec2-user@$STAX_PUB_IP:~ > /dev/null
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP 'chmod 0755 dockconnect' > /dev/null
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP 'chmod 0755 fleetstats' > /dev/null
   echo "done"
   echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     cleaning files: "
   rm /tmp/docker_hosts; rm /tmp/dockconnect; rm /tmp/fleetstats
@@ -314,7 +341,14 @@ stax-getdockerips(){
 }
 
 stax-connect(){
-  ssh -q -i ~/.ssh/$STAX_KEY.pem ec2-user@$STAX_PUB_IP
+  ssh $SSH_OPTIONS ec2-user@$STAX_PUB_IP
+}
+
+stax-destroy-key(){
+    echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     deleting $STAX_NAME key: "
+    $aws ec2 delete-key-pair --key-name "$STAX_NAME" > /dev/null
+    rm -f $STAX_KEY_FILE
+    echo "done"
 }
 
 stax-destroy-files(){
@@ -340,6 +374,7 @@ stax-destroy(){
       echo "done"
       stax-destroy-bucket
       stax-destroy-files
+      stax-destroy-key
       echo -n "${yellow}[ ${cyan}----${yellow} ]${reset}     recording $STAX_NAME deletion time for audit: "
       touch $STAX_DIR/audit/`date +'%Y%m%d-%H%M%S'`-destroyed-$STAX_NAME
       echo "done"
@@ -358,7 +393,7 @@ stax-generate(){
     RANDOM_NUM=$((RANDOM%99999+10001))
     STAX_NAME="vpc-$STAX_PRE_NAME-$RANDOM_NUM-$RANDOM_NAM"
     # initialize sed command
-    sed="sed -e s/@STAX_NAME@/$STAX_NAME/g"
+    sed="sed -e s/@STAX_NAME@/$STAX_NAME/ -e s/@KEY_NAME@/$STAX_NAME/"
     # see if we need to substitute for SSH_FROM
     if grep -q SSH_FROM "$config" > /dev/null 2>&1; then
         SSH_FROM="$(curl -s http://icanhazip.com)\/32"
@@ -375,7 +410,7 @@ stax-generate(){
             echo "$pkg: failed to get discovery URL"
             exit 1
         fi
-        sed="$sed -e s|@DISCOVERY_URL@|$DISCOVERY_URL|g"
+        sed="$sed -e s|@DISCOVERY_URL@|$DISCOVERY_URL|"
     fi
     if ! $sed "$config" > "$config_tmp"; then
         echo "$pkg: sed failed to replace elements in $config: $sed"
@@ -389,7 +424,10 @@ stax-logo
 stax-preflight
 
 if [ -f "$STAX_NAME_FILE" ]; then
-  STAX_NAME=$(<$STAX_NAME_FILE)
+    STAX_NAME=$(<$STAX_NAME_FILE)
+    STAX_KEY="$STAX_NAME"
+    STAX_KEY_FILE="$STAX_DIR/$STAX_NAME.pem"
+    SSH_OPTIONS="$SSH_OPTIONS -i $STAX_KEY_FILE"
 fi
 
 
