added config and template files, updated stax for vpc aktion

diff --git a/stax b/stax
--- a/stax
+++ b/stax
@@ -32,6 +32,7 @@ echo "Usage: stax command"
 
 echo; echo "Commands:"
 echo "  create            Create new stax"
+echo "  create-vpc        Create new VPC stax"
 echo "  describe | desc   Describe created stax"
 echo "  getip             Get the public, or elastic IP of created stax"
 echo "  destroy           Destroy existing stax"
@@ -90,6 +91,17 @@ stax-create(){
     --parameters "$(<config.json.tmp)"
 }
 
+stax-create-vpc(){
+  stax-generate-vpc
+  STAX_NAME="vpc.$STAX_PRE_NAME-$RANDOM_NUM-$RANDOM_NAM"
+  echo $STAX_NAME > ~/.stax/stax-name
+  echo "${yellow}[ ${cyan}----${yellow} ]${reset} creating $CLUSTER_SIZE nodes - $STAX_NAME"
+  aws --color on cloudformation create-stack \
+    --stack-name $STAX_NAME \
+    --template-body file://$SCRIPT_PATH/templates/cloudformation-template-vpc.json \
+    --parameters "$(<config-vpc.json.tmp)"
+}
+
 stax-describe(){
   aws cloudformation describe-stacks --stack-name $STAX_NAME > /dev/null 2>&1 || { echo "${yellow}[ ${cyan}----${yellow} ]${reset} no stax defined"; rm $HOME/.stax/stax-name; exit 1; }
   echo "${yellow}[ ${cyan}----${yellow} ]${reset} describe $STAX_NAME"
@@ -123,6 +135,16 @@ stax-generate(){
   RANDOM_NUM=$((RANDOM%99999+10001))
 }
 
+stax-generate-vpc(){
+  if [ ! -f config-vpc.json ]; then
+     echo "config-vpc.json not configured, copy example and configure'. Aborting."; exit 1
+  fi
+  cp config-vpc.json config.json.tmp
+  NUMW=`wc -l < config/stax-words`
+  RANDOM_NAM=`head -$((${RANDOM} % ${NUMW} + 1)) config/stax-words | tail -1`
+  RANDOM_NUM=$((RANDOM%99999+10001))
+}
+
 clear
 stax-colors
 stax-logo
@@ -146,6 +168,19 @@ if [[ "$1" == "create" ]]; then
     exit 1
   else
     stax-create
+    stax-describe
+    aws cloudformation describe-stacks --stack-name $STAX_NAME > ~/.stax/$STAX_NAME.json
+    rm config.json.tmp
+    exit 0
+  fi
+fi
+
+if [[ "$1" == "create-vpc" ]]; then
+  if [ -f $HOME/.stax/stax-name ]; then
+    echo "${yellow}[ ${red}ERRR${yellow} ]${reset} existing stax defined, exiting";
+    exit 1
+  else
+    stax-create-vpc
     stax-describe
     aws cloudformation describe-stacks --stack-name $STAX_NAME > ~/.stax/$STAX_NAME.json
     rm config.json.tmp
